//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3634
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSFramework3.WebServiceReference.WCF_PurchaseModuleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_PurchaseModuleService.IPurchaseModuleService")]
    public interface IPurchaseModuleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseModuleService/PO_Delete", ReplyAction="http://tempuri.org/IPurchaseModuleService/PO_DeleteResponse")]
        bool PO_Delete(byte[] loginTicket, string docNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseModuleService/PO_GetBusinessByKey", ReplyAction="http://tempuri.org/IPurchaseModuleService/PO_GetBusinessByKeyResponse")]
        byte[] PO_GetBusinessByKey(byte[] loginTicket, string docNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseModuleService/PO_GetReportData", ReplyAction="http://tempuri.org/IPurchaseModuleService/PO_GetReportDataResponse")]
        byte[] PO_GetReportData(byte[] loginTicket, string DocNoFrom, string DocNoTo, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseModuleService/PO_GetSummaryByParam", ReplyAction="http://tempuri.org/IPurchaseModuleService/PO_GetSummaryByParamResponse")]
        byte[] PO_GetSummaryByParam(byte[] loginTicket, string docNoFrom, string docNoTo, System.DateTime docDateFrom, System.DateTime docDateTo, string StockCode, string Customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseModuleService/PO_Update", ReplyAction="http://tempuri.org/IPurchaseModuleService/PO_UpdateResponse")]
        byte[] PO_Update(byte[] loginTicket, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseModuleService/PO_CheckNoExists", ReplyAction="http://tempuri.org/IPurchaseModuleService/PO_CheckNoExistsResponse")]
        bool PO_CheckNoExists(byte[] loginTicket, string keyValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseModuleService/PO_ApprovalBusiness", ReplyAction="http://tempuri.org/IPurchaseModuleService/PO_ApprovalBusinessResponse")]
        void PO_ApprovalBusiness(byte[] loginTicket, string keyValue, string flagApp, string appUser, System.DateTime appDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPurchaseModuleServiceChannel : CSFramework3.WebServiceReference.WCF_PurchaseModuleService.IPurchaseModuleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PurchaseModuleServiceClient : System.ServiceModel.ClientBase<CSFramework3.WebServiceReference.WCF_PurchaseModuleService.IPurchaseModuleService>, CSFramework3.WebServiceReference.WCF_PurchaseModuleService.IPurchaseModuleService {
        
        public PurchaseModuleServiceClient() {
        }
        
        public PurchaseModuleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseModuleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseModuleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseModuleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PO_Delete(byte[] loginTicket, string docNo) {
            return base.Channel.PO_Delete(loginTicket, docNo);
        }
        
        public byte[] PO_GetBusinessByKey(byte[] loginTicket, string docNo) {
            return base.Channel.PO_GetBusinessByKey(loginTicket, docNo);
        }
        
        public byte[] PO_GetReportData(byte[] loginTicket, string DocNoFrom, string DocNoTo, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.PO_GetReportData(loginTicket, DocNoFrom, DocNoTo, DateFrom, DateTo);
        }
        
        public byte[] PO_GetSummaryByParam(byte[] loginTicket, string docNoFrom, string docNoTo, System.DateTime docDateFrom, System.DateTime docDateTo, string StockCode, string Customer) {
            return base.Channel.PO_GetSummaryByParam(loginTicket, docNoFrom, docNoTo, docDateFrom, docDateTo, StockCode, Customer);
        }
        
        public byte[] PO_Update(byte[] loginTicket, byte[] data) {
            return base.Channel.PO_Update(loginTicket, data);
        }
        
        public bool PO_CheckNoExists(byte[] loginTicket, string keyValue) {
            return base.Channel.PO_CheckNoExists(loginTicket, keyValue);
        }
        
        public void PO_ApprovalBusiness(byte[] loginTicket, string keyValue, string flagApp, string appUser, System.DateTime appDate) {
            base.Channel.PO_ApprovalBusiness(loginTicket, keyValue, flagApp, appUser, appDate);
        }
    }
}
